name: Commitlint

on: 
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install @commitlint/cli @commitlint/config-conventional

      - name: Validate all commits of PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
